language: generic
dist: trusty
sudo: required
group: edge

os:
    - osx
    - linux

install:
    case $TRAVIS_OS_NAME in
    osx)
    brew update &&
    brew install coq ;;
    linux)
    wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin &&
    opam install coq -y &&
    eval $(opam config env) ;;
    esac
script:
    make -C bast0-coq -j
